server:
  port: 8083

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: ecovida-postgres
    password: A2QjQxdSIs9rNJ8YbXewmraEcqMz45BDDSzVFjWzkw5XjxP9Q1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/auth/realms/SpringBootKeycloak
management:
  endpoint:
    health:
      probes:
        enabled: true
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,refresh
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  feign:
    product-service:
      url: http://localhost:8082