server:
  port: 8084

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/orders_db
    username: ecovida-postgres
    password: A2QjQxdSIs9rNJ8YbXewmraEcqMz45BDDSzVFjWzkw5XjxP9Q1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/auth/realms/SpringBootKeycloak

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  feign:
    user-service:
      url: http://localhost:8081
    product-service:
      url: http://localhost:8082
    inventory-service:
      url: http://localhost:8083