server:
  port: 8082

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/products_db
    username: ecovida-postgres
    password: A2QjQxdSIs9rNJ8YbXewmraEcqMz45BDDSzVFjWzkw5XjxP9Q1
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/auth/realms/SpringBootKeycloak

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  feign:
    user-service:
      url: http://localhost:8081