server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: ecovida-postgres
    password: A2QjQxdSIs9rNJ8YbXewmraEcqMz45BDDSzVFjWzkw5XjxP9Q1
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/auth/realms/SpringBootKeycloak
management:
  endpoint:
    health:
      probes:
        enabled: true
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,refresh
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

app:
  feign:
    product-service:
      url: http://localhost:8082
    inventory-service:
      url: http://localhost:8083
    order-service:
      url: http://localhost:8084